### ISSUE TITLE
Limma R package not loading

### ISSUE THREAD

**Issue by mjacksonhill** [transXpress/transXpress#26]
I get an error in kallisto.log:

`> library(edgeR)`
`Loading required package: limma`
`Error: package or namespace load failed for 'limma':`
    `package 'limma' was installed before R 4.0.0: please re-install it`
`Error: package 'limma' could not be loaded`
`Execution halted`

running `conda install -c bioconda bioconductor-limma` from my transxpress instance only tells me that it is already installed. Running library(limma) from the conda R also gives the same error.

my .libPaths from Conda gives me:
`> .libPaths()`
`[1] "/home/hill/R/x86_64-conda_cos6-linux-gnu-library/4.0"`
`[2] "/nfs/apps/lib/R/3.6/site-library.2020q2"`
`[3] "/home/hill/miniconda/envs/transxpress/lib/R/library"`

**Comment by mjacksonhill** [comment]
Running the command `unset R_LIBS_SITE` before `conda activate transxpress` allows the `library(limma)` command within the conda R to execute successfully. I'll see if this works in the context of the larger pipeline.

**Comment by mjacksonhill** [comment]
Now it exits out at a different stage (see attached log) 
[trinity_exN50.log](https://github.com/transXpress/transXpress-snakemake/files/5491405/trinity_exN50.log)

**Comment by CalounovaT** [comment]
Hi,
thank you for your report.
Could you please try whether using this [Snakefile]( https://github.com/CalounovaT/transXpress-snakemake/blob/fix/Snakefile) instead resolves the issue? 

The plot generated at this stage by Trinity is now called "ExN50_plot.pdf" while in the older version the name was different. If that is the issue, using this updated Snakefile should resolve that.

**Comment by tomas-pluskal** [comment]
@CalounovaT We should mention the issue with the R_LIBS_SITE variable in the README.

**Comment by mjacksonhill** [comment]
Using the new Snakefile (with `unset R_LIBS_SITE` as well) seems to have resolved this issue!
