### ISSUE TITLE
tmhmm.py not working with numpy.ufunc

### ISSUE THREAD

**Issue by mjacksonhill** [transXpress/transXpress#27]
I'm getting the following error in tmhmm.log:

[tmhmm_1.log](https://github.com/transXpress/transXpress-snakemake/files/5501743/tmhmm_1.log)

**Comment by CalounovaT** [comment]
Could you please specify which numpy version are you using? 
Execute this command:
`conda list | grep numpy`

**Comment by mjacksonhill** [comment]
Sure!

`numpy                     1.14.6          py36_blas_openblashd3ea46f_200  [blas_                                                                            openblas]  conda-forge`

**Comment by CalounovaT** [comment]
I had the same issue as you when using numpy 1.14, using numpy 1.16 instead resolved it in my case.
We made some changes recently in the conda dependencies installation and numpy version 1.16 is now being installed.

Hope using numpy 1.16 resolves it for you as well.

**Comment by mjacksonhill** [comment]
I made a new conda environment to use all the updated dependencies just in case, and now I'm running into an error with asyncio. I'm getting the error `AttributeError: module 'asyncio' has no attribute 'create_task'`, which I see is because the create_task attribute was introduced in Python 3.7, while transXpress now uses Python 3.6.

**Comment by CalounovaT** [comment]
There seems to be a problem with this in the newest version of Snakemake (5.27.4, published on November 3, 2020) https://github.com/snakemake/snakemake/issues/725 
When using the second newest conda available version of Snakemake - 5.26.1 there is no problem with this, using Python 3.6 is fine.

Was your Snakemake version 5.27.4?

**Comment by mjacksonhill** [comment]
Yes, it was. Everything seems to be working now with my older transXpress installation with 5.26.1 (installed before the dependency changes) while my newer installation with 5.27.4 was giving me this error. I will downgrade to 5.26.1 in my newer conda instance and see if that lets everything work nicely.

**Comment by tomas-pluskal** [comment]
I think this issue should be fixed in snakemake 5.28.0: https://github.com/snakemake/snakemake/releases/tag/v5.28.0
@CalounovaT could you test it and update our README accordingly?
