### ISSUE TITLE
snakemake min version

### ISSUE THREAD

**Issue by mmokrejs** [transXpress/transXpress#49]
Hi,
  the `README.md` states >=5.4.2 while `Snakefile` states >=5.4.1.  Which one is correct?

**Comment by lexi-k** [comment]
Hi, probably a bit late but for the sake of transparency: IMHO the version is always the latest available one. In the `Snakefile` there is a minimal version requirement of [5.4.1](https://github.com/transXpress/transXpress/blob/master/Snakefile#L12) and in the conda env file which is installing snakemake tehre is also just minimal version of [3.9.0](https://github.com/transXpress/transXpress/blob/master/envs/default.yaml#L7) so it should install always the latest one which to currently is `7.32.3`. This can be confirmed by running `pip list | grep snakemake` in the transxpress environment which outputs `snakemake                     7.32.3`.
