### ISSUE TITLE
Implement rnaSPAdes?

### ISSUE THREAD

**Issue by photocyte** [transXpress/transXpress#6]
I imagine it wouldn't be too difficult.  rnaSPAdes expects to be run on a single node, and has pretty mature internal pipelining that doesn't do anything funny, so implementation of that block should be straightforward.

The trick is deriving the YAML read file input to rnaSPAdes from the "samples.txt" file, but I already have a janky bash script node on the Nextflow side which does that.

Does also require having the trimmomatic be split out into a separate process.

Having both Trinity and rnaSPAdes for both the Snakemake and Nextflow versions would be a good selling point for a 1.0 paper.

Otherwise, can push this to the 2.0 milestone.

**Comment by tomas-pluskal** [comment]
Sure, we can do that. The downstream expression analysis also requires a gene-trans-map file, but I suppose for the rnaSPAdes assembly we can simply generate a dummy file that maps each transcript as a separate gene.

**Comment by tomas-pluskal** [comment]
Added SPAdes to the installation instructions https://github.com/transXpress/transXpress-snakemake/commit/b139ac6e6f716d2d9c2a002f46b43e28da3bb51b

**Comment by photocyte** [comment]
Basics implemented here: bf8814fb21f36735db76fd0647bc7e4fb8aa32d4.  Still need to make a gene trans map, so it can feed into the rest of the pipeline.

Note: I think the gene trans map may only be useful for RSEM.  Kallisto I believe calculates "similar isoforms" for the maximum liklihood assigning of reads to isoforms from a kmer graph of the transcripts (so, doesn't need to be told the relationship of the transcripts)

**Comment by tomas-pluskal** [comment]
Cool!

We can drop the gene_trans_map, but then we will have to reimplement the align_and_estimate_abundance script.

**Comment by photocyte** [comment]
Yes, I'll give it some thought.  Some notes:

bowtie2 alignments to the transcripts can be nice: (for troubleshooting assembly issues.  Maybe a bit heavy to produce by default though), but not necessary for kallisto.

Ultimately it comes down to what files we want to produce.  e.g: 
1) TPM per transcript (all samples?)
2) TPMs across provided samples, ideally with between sample normalization (not sure if align_and_estimate_abundance is doing this internally, or how it is doing it)

**Comment by tomas-pluskal** [comment]
rnaspades seems to be working, what remains is the K-mer size setting. I suppose we can add rnaspades_parameters to config.yaml, same as we have for trinity.

**Comment by Shellfishgene** [comment]
Why a fake gene_trans_map? RNASpades also produces transcripts annotated with genes, something simple like
```perl -ne 'if ( /^>/ ) { $_ =~ s/>//; /_(g[0-9]+)_i[0-9]+/; print "$1\t$_" }' transcripts.fasta```
can produce a mapping file, no?

**Comment by mmokrejs** [comment]
Seems `transcriptome_stats.txt` file always speaks of `trinity` although `rnaspades` may have been used for assembly.

**Comment by mmokrejs** [comment]
> Seems `transcriptome_stats.txt` file always speaks of `trinity` although `rnaspades` may have been used for assembly. Seems the `trinity` string could be replaced by `sed` on the line https://github.com/transXpress/transXpress/blob/master/Snakefile#357 depening on `config["assembler"]=="rnaspades"` but we need that in shell syntax unlike python.

This is tackled in https://github.com/transXpress/transXpress/pull/44/commits/24b748258e6a50f9f29ea2f36e6bdd96669f7094
